/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#15121b',
        'surface-dim': '#15121b',
        'surface-bright': '#3b3742',
        'surface-container-lowest': '#0f0d15',
        'surface-container-low': '#1d1a23',
        'surface-container': '#211e27',
        'surface-container-high': '#2c2832',
        'surface-container-highest': '#37333d',
        'on-surface': '#e7e0ed',
        'on-surface-variant': '#cbc3d7',
        'inverse-surface': '#e7e0ed',
        'inverse-on-surface': '#322f39',
        outline: '#958ea0',
        'outline-variant': '#494454',
        'surface-tint': '#d0bcff',
        primary: '#d0bcff',
        'primary-container': '#a078ff',
        'on-primary': '#3c0091',
        'on-primary-container': '#340080',
        'inverse-primary': '#6d3bd7',
        secondary: '#4cd7f6',
        'secondary-container': '#03b5d3',
        'on-secondary': '#003640',
        'on-secondary-container': '#00424e',
        tertiary: '#ffb869',
        'tertiary-container': '#ca801e',
        'on-tertiary': '#482900',
        'on-tertiary-container': '#3f2300',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        background: '#15121b',
        'on-background': '#e7e0ed',
        'bg-canvas': '#090A0F',
        'surface-panel': '#12131A',
        'surface-elevated': '#1A1C26',
        'border-subtle': '#262838',
        'text-main': '#F4F4F5',
        'text-muted': '#71717A',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      animation: {
        'pulse-subtle': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      }
    },
  },
  plugins: [],
}
