/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          colors: {
              "on-surface": "#dee5ff",
              "error-container": "#a70138",
              "secondary-dim": "#58e7ab",
              "primary-dim": "#8455ef",
              "surface-tint": "#ba9eff",
              "on-surface-variant": "#a3aac4",
              "secondary": "#69f6b8",
              "on-error": "#490013",
              "primary-fixed": "#ae8dff",
              "on-primary-container": "#2b006e",
              "inverse-surface": "#faf8ff",
              "on-tertiary-fixed-variant": "#535b71",
              "on-error-container": "#ffb2b9",
              "on-tertiary": "#525a70",
              "on-tertiary-fixed": "#373f54",
              "tertiary": "#eef0ff",
              "primary": "#ba9eff",
              "surface-container-high": "#141f38",
              "error": "#ff6e84",
              "error-dim": "#d73357",
              "tertiary-fixed": "#dae2fd",
              "on-secondary-fixed": "#00452d",
              "surface-bright": "#1f2b49",
              "surface": "#060e20",
              "on-secondary-container": "#e1ffec",
              "tertiary-dim": "#ccd4ee",
              "surface-container-low": "#091328",
              "surface-container": "#0f1930",
              "on-secondary-fixed-variant": "#006544",
              "on-primary-fixed-variant": "#370086",
              "tertiary-fixed-dim": "#ccd4ee",
              "on-primary-fixed": "#000000",
              "surface-container-lowest": "#000000",
              "inverse-on-surface": "#4d556b",
              "on-tertiary-container": "#4a5167",
              "primary-container": "#ae8dff",
              "surface-dim": "#060e20",
              "on-background": "#dee5ff",
              "secondary-fixed": "#69f6b8",
              "surface-variant": "#192540",
              "inverse-primary": "#6e3bd7",
              "secondary-container": "#006c49",
              "surface-container-highest": "#192540",
              "on-secondary": "#005a3c",
              "outline-variant": "#40485d",
              "on-primary": "#39008c",
              "secondary-fixed-dim": "#58e7ab",
              "tertiary-container": "#dae2fd",
              "background": "#060e20",
              "primary-fixed-dim": "#a27cff",
              "outline": "#6d758c"
          },
          fontFamily: {
              "headline": ["Plus Jakarta Sans", "sans-serif"],
              "body": ["Inter", "sans-serif"],
              "label": ["Inter", "sans-serif"]
          },
          borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
      },
  },
  plugins: [],
}
