/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ffb95f",
        "primary-fixed-dim": "#c0c1ff",
        "surface-variant": "#353437",
        "on-tertiary": "#472a00",
        "primary": "#c0c1ff",
        "on-secondary": "#003824",
        "surface-container-lowest": "#0e0e10",
        "on-tertiary-container": "#3e2400",
        "outline": "#908fa0",
        "surface-container": "#201f22",
        "surface-container-low": "#1c1b1d",
        "on-surface": "#e5e1e4",
        "background": "#131315",
        "on-error": "#690005",
        "secondary-fixed-dim": "#4edea3",
        "on-primary-fixed": "#07006c",
        "on-primary-container": "#0d0096",
        "surface-container-high": "#2a2a2c",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#005236",
        "inverse-primary": "#494bd6",
        "primary-fixed": "#e1e0ff",
        "on-secondary-fixed": "#002113",
        "on-tertiary-fixed": "#2a1700",
        "inverse-surface": "#e5e1e4",
        "tertiary-fixed": "#ffddb8",
        "surface-bright": "#39393b",
        "error-container": "#93000a",
        "secondary-container": "#00a572",
        "surface-container-highest": "#353437",
        "on-tertiary-fixed-variant": "#653e00",
        "on-primary-fixed-variant": "#2f2ebe",
        "primary-container": "#8083ff",
        "outline-variant": "#464554",
        "on-background": "#e5e1e4",
        "error": "#ffb4ab",
        "surface-tint": "#c0c1ff",
        "on-secondary-container": "#00311f",
        "secondary": "#4edea3",
        "on-primary": "#1000a9",
        "tertiary": "#ffb95f",
        "inverse-on-surface": "#313032",
        "tertiary-container": "#ca8100",
        "surface-dim": "#131315",
        "secondary-fixed": "#6ffbbe",
        "on-surface-variant": "#c7c4d7",
        "surface": "#131315"
      },
      spacing: {
        "space-lg": "1rem",
        "space-xs": "0.25rem",
        "gutter": "1rem",
        "margin": "1.5rem",
        "space-md": "0.75rem",
        "space-sm": "0.5rem",
        "space-xl": "1.5rem"
      },
      fontFamily: {
        "headline-sm": ["Inter", "sans-serif"],
        "code-metric": ["Inter", "monospace"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "title": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "inter": ["Inter", "sans-serif"],
        "serif": ["Merriweather", "serif"],
        "mono": ["Roboto Mono", "monospace"],
        "cinzel": ["Cinzel", "serif"]
      },
      fontSize: {
        "headline-sm": ["1.125rem", { lineHeight: "1.5rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "code-metric": ["0.75rem", { lineHeight: "1rem", letterSpacing: "-0.01em", fontWeight: "500" }],
        "label-sm": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.025em", fontWeight: "600" }],
        "body-md": ["0.875rem", { lineHeight: "1.375rem", fontWeight: "400" }],
        "title": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "-0.005em", fontWeight: "600" }],
        "label-md": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.01em", fontWeight: "500" }],
        "display": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "-0.025em", fontWeight: "600" }],
        "body-lg": ["1rem", { lineHeight: "1.5rem", fontWeight: "400" }],
        "headline-md": ["1.25rem", { lineHeight: "1.75rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg": ["1.75rem", { lineHeight: "2.25rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["1.5rem", { lineHeight: "2rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-sm": ["0.75rem", { lineHeight: "1.125rem", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
}
