/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#5f4100",
        "on-background": "#dfe2eb",
        "error-container": "#93000a",
        "secondary-fixed": "#ffdeaa",
        "surface-container-low": "#181c22",
        "outline-variant": "#414752",
        "surface-container-lowest": "#0a0e14",
        "inverse-surface": "#dfe2eb",
        "secondary-container": "#bd8708",
        "surface-tint": "#a2c9ff",
        "on-surface": "#dfe2eb",
        "on-tertiary-fixed": "#002106",
        "surface-container-high": "#262a31",
        "primary": "#a2c9ff",
        "primary-container": "#58a6ff",
        "surface-variant": "#31353c",
        "tertiary-fixed-dim": "#7bdb80",
        "on-secondary-fixed": "#271900",
        "surface-container": "#1c2026",
        "outline": "#8b919d",
        "surface-dim": "#10141a",
        "on-error": "#690005",
        "tertiary": "#7bdb80",
        "tertiary-container": "#58b760",
        "secondary": "#fabc45",
        "primary-fixed": "#d3e4ff",
        "on-surface-variant": "#c0c7d4",
        "on-tertiary-container": "#004413",
        "error": "#ffb4ab",
        "surface-bright": "#353940",
        "surface": "#10141a",
        "on-secondary": "#422c00",
        "on-tertiary": "#00390e",
        "primary-fixed-dim": "#a2c9ff",
        "secondary-fixed-dim": "#fabc45",
        "inverse-on-surface": "#2d3137",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#0060aa",
        "on-primary-container": "#003a6b",
        "on-primary-fixed-variant": "#004882",
        "on-primary": "#00315c",
        "surface-container-highest": "#31353c",
        "on-tertiary-fixed-variant": "#005319",
        "on-primary-fixed": "#001c38",
        "on-secondary-container": "#392600",
        "tertiary-fixed": "#97f999",
        "background": "#10141a"
      },
      spacing: {
        "space-md": "1rem",
        "space-sm": "0.5rem",
        "space-xl": "2.5rem",
        "gutter": "1rem",
        "space-xs": "0.25rem",
        "margin-desktop": "2rem",
        "gutter-desktop": "1.5rem",
        "margin": "1rem",
        "space-lg": "1.5rem"
      },
      fontFamily: {
        "label-caps": ["JetBrains Mono", "monospace"],
        "telemetry-sm": ["JetBrains Mono", "monospace"],
        "headline-md": ["Outfit", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-xl-mobile": ["Outfit", "sans-serif"],
        "telemetry-lg": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "headline-xl": ["Outfit", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
        "headline-lg-mobile": ["Outfit", "sans-serif"],
        "telemetry-md": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"]
      }
    }
  },
  plugins: [],
}
