/**
 * Flocking Simulation Presets
 */

export const PRESETS = [
  {
    id: 'murmuration',
    name: 'Starling Murmuration',
    description: 'Silky, synchronized aerial flock with harmonic sweeping maneuvers.',
    icon: 'Bird',
    boids: 1600,
    weightSep: 1.8,
    weightAli: 1.6,
    weightCoh: 1.2,
    weightTarget: 0.5,
    neighborRadius: 9.0,
    separationRadius: 3.2,
    maxSpeed: 1.5,
    minSpeed: 0.7,
    maxForce: 0.09,
    colorTheme: 'cyan',
    targetActive: true,
    predatorActive: false,
  },
  {
    id: 'oceanic',
    name: 'Deep Sea School',
    description: 'Dense, undulating aquatic school with low turbulence and steady drift.',
    icon: 'Fish',
    boids: 2000,
    weightSep: 1.4,
    weightAli: 1.8,
    weightCoh: 1.5,
    weightTarget: 0.3,
    neighborRadius: 7.5,
    separationRadius: 2.5,
    maxSpeed: 1.1,
    minSpeed: 0.4,
    maxForce: 0.05,
    colorTheme: 'ocean',
    targetActive: true,
    predatorActive: false,
  },
  {
    id: 'predator',
    name: 'Apex Predator Hunt',
    description: 'Autonomous cyber predator agent stalking and scattering the defensive flock.',
    icon: 'Flame',
    boids: 1400,
    weightSep: 2.4,
    weightAli: 1.2,
    weightCoh: 0.9,
    weightTarget: 0.2,
    neighborRadius: 10.0,
    separationRadius: 4.0,
    maxSpeed: 1.7,
    minSpeed: 0.8,
    maxForce: 0.12,
    colorTheme: 'thermal',
    targetActive: false,
    predatorActive: true,
  },
  {
    id: 'swarm',
    name: 'Chaotic Insect Swarm',
    description: 'Erratic, high-entropy micro-drone swarm with tight evasive repulsion.',
    icon: 'Bug',
    boids: 1200,
    weightSep: 2.8,
    weightAli: 0.4,
    weightCoh: 1.4,
    weightTarget: 0.8,
    neighborRadius: 6.0,
    separationRadius: 3.5,
    maxSpeed: 2.2,
    minSpeed: 1.0,
    maxForce: 0.18,
    colorTheme: 'emerald',
    targetActive: true,
    predatorActive: false,
  },
  {
    id: 'quantum',
    name: 'Quantum Particle Vortex',
    description: 'High-speed luminous particle stream orbiting a fluctuating singularity.',
    icon: 'Zap',
    boids: 2400,
    weightSep: 1.2,
    weightAli: 1.4,
    weightCoh: 1.8,
    weightTarget: 1.1,
    neighborRadius: 11.0,
    separationRadius: 2.2,
    maxSpeed: 2.0,
    minSpeed: 0.9,
    maxForce: 0.14,
    colorTheme: 'neon',
    targetActive: true,
    predatorActive: false,
  },
];
