/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#131315',
        'surface-dim': '#131315',
        'surface-bright': '#39393b',
        'surface-container-lowest': '#0e0e10',
        'surface-container-low': '#1c1b1d',
        'surface-container': '#201f22',
        'surface-container-high': '#2a2a2c',
        'surface-container-highest': '#353437',
        'on-surface': '#e5e1e4',
        'on-surface-variant': '#bdc8d1',
        'inverse-surface': '#e5e1e4',
        'inverse-on-surface': '#313032',
        'outline': '#87929a',
        'outline-variant': '#3e484f',
        'surface-tint': '#7bd0ff',
        'primary': '#8ed5ff',
        'on-primary': '#00354a',
        'primary-container': '#38bdf8',
        'on-primary-container': '#004965',
        'inverse-primary': '#00668a',
        'secondary': '#c8c5ca',
        'on-secondary': '#303033',
        'secondary-container': '#47464a',
        'on-secondary-container': '#b6b4b8',
        'tertiary': '#cdcbd6',
        'on-tertiary': '#2f3038',
        'tertiary-container': '#b1b0ba',
        'on-tertiary-container': '#43434b',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#c4e7ff',
        'primary-fixed-dim': '#7bd0ff',
        'on-primary-fixed': '#001e2c',
        'on-primary-fixed-variant': '#004c69',
        'secondary-fixed': '#e4e1e6',
        'secondary-fixed-dim': '#c8c5ca',
        'on-secondary-fixed': '#1b1b1e',
        'on-secondary-fixed-variant': '#47464a',
        'tertiary-fixed': '#e3e1ec',
        'tertiary-fixed-dim': '#c6c5cf',
        'on-tertiary-fixed': '#1a1b22',
        'on-tertiary-fixed-variant': '#46464e',
        'background': '#131315',
        'on-background': '#e5e1e4',
        'surface-variant': '#353437',
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        '2xl': '2rem',
        'full': '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        'gutter': '1rem',
        'gutter-desktop': '1.5rem',
        'margin': '1rem',
        'margin-tablet': '1.5rem',
        'margin-desktop': '2.5rem',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        'body': ['Inter', 'sans-serif'],
        'mono-tech': ['JetBrains Mono', 'monospace'],
      },
      boxShadow: {
        'photonic': '0 0 20px -2px rgba(56, 189, 248, 0.35), 0 0 0 1px #38bdf8',
        'photonic-lg': '0 0 30px rgba(56, 189, 248, 0.50)',
        'darkroom-card': '0 8px 30px rgba(0, 0, 0, 0.6), 0 0 1px 1px rgba(255, 255, 255, 0.05)',
      },
      animation: {
        'pulse-subtle': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'shimmer': 'shimmer 2s linear infinite',
      },
      keyframes: {
        shimmer: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
      },
    },
  },
  plugins: [],
};
