#!/usr/bin/env php
<?php
// CLI NestTalk – Recursive Comment System
// Author: Generated by GitHub Copilot (Raptor mini (Preview))

$DB_FILE = __DIR__ . '/comments.json';

function loadComments() {
    global $DB_FILE;
    if (!file_exists($DB_FILE)) {
        file_put_contents($DB_FILE, json_encode([], JSON_PRETTY_PRINT));
    }
    $data = json_decode(file_get_contents($DB_FILE), true);
    return $data ?: [];
}

function saveComments($comments) {
    global $DB_FILE;
    // use array_values to keep JSON as plain array
    file_put_contents($DB_FILE, json_encode(array_values($comments), JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE));
}

function getNextId($comments) {
    $max = 0;
    foreach ($comments as $c) {
        if (isset($c['id']) && $c['id'] > $max) $max = $c['id'];
    }
    return $max + 1;
}

function getChildren($comments, $parentId) {
    $children = array_filter($comments, function($c) use ($parentId) {
        // normalize null vs null-like
        return ($c['parent_id'] === $parentId);
    });
    // sort by id
    usort($children, function($a,$b){ return $a['id'] <=> $b['id']; });
    return $children;
}

function displayHeader($title = 'DISCUSSION THREAD') {
    $line = str_repeat('=', 60);
    echo "\n$line\n";
    echo "   $title\n";
    echo "$line\n";
}

// Recursive display with nice ASCII threads
function showComments($comments, $parentId = null, $prefixParts = []) {
    $children = getChildren($comments, $parentId);
    $count = count($children);
    if ($count === 0) return;

    for ($i = 0; $i < $count; $i++) {
        $c = $children[$i];
        $isLast = ($i === $count - 1);

        // build indent from prefixParts
        $indent = '';
        foreach ($prefixParts as $part) {
            $indent .= $part ? "   |" : "    ";
        }

        if ($parentId === null) {
            // top-level
            echo "{$indent}[ID: {$c['id']}] {$c['author']}: {$c['text']}\n";
        } else {
            echo "{$indent}   +-- [ID: {$c['id']}] {$c['author']}: {$c['text']}\n";
        }

        // if this comment has children, show vertical connector then recurse
        $grandChildren = getChildren($comments, $c['id']);
        if (count($grandChildren) > 0) {
            // show connector line
            echo $indent . "   |\n";
            // for next level, append whether there's a next sibling (so pipes continue)
            $nextPrefixParts = $prefixParts;
            $nextPrefixParts[] = !$isLast;
            showComments($comments, $c['id'], $nextPrefixParts);
        }
    }
}

function postComment(&$comments, $author, $text, $parentId = null) {
    $id = getNextId($comments);
    $comments[] = [
        'id' => $id,
        'parent_id' => $parentId,
        'author' => $author,
        'text' => $text,
        'created_at' => date('c')
    ];
    saveComments($comments);
    return $id;
}

function findDescendants($comments, $id) {
    $desc = [];
    $direct = getChildren($comments, $id);
    foreach ($direct as $d) {
        $desc[] = $d['id'];
        $desc = array_merge($desc, findDescendants($comments, $d['id']));
    }
    return $desc;
}

function deleteBranch(&$comments, $id) {
    $toDelete = [$id];
    $toDelete = array_merge($toDelete, findDescendants($comments, $id));
    $comments = array_filter($comments, function($c) use ($toDelete) { return !in_array($c['id'], $toDelete); });
    // reindex to normal array
    $comments = array_values($comments);
    saveComments($comments);
    return $toDelete;
}

function findAncestor($comments, $id, $levelsUp = 3) {
    // find ancestor $levelsUp levels above $id
    $map = [];
    foreach ($comments as $c) $map[$c['id']] = $c['parent_id'];

    $current = $id;
    for ($i=0; $i<$levelsUp; $i++) {
        if (!isset($map[$current]) || $map[$current] === null) return null;
        $current = $map[$current];
    }
    return $current;
}

function getCommentById($comments, $id) {
    foreach ($comments as $c) if ($c['id'] == $id) return $c;
    return null;
}

// Simple CLI helpers
function prompt($label) {
    echo $label;
    $line = trim(fgets(STDIN));
    return $line;
}

// Boot
$comments = loadComments();

// Main loop
while (true) {
    displayHeader('DISCUSSION THREAD: "Learning PHP CLI"');
    echo "[1] View Thread\n";
    echo "[2] Post Comment\n";
    echo "[3] Reply to Comment (by ID)\n";
    echo "[4] Delete Comment (Delete branch)\n";
    echo "[5] Find Great-Grandparent\n";
    echo "[6] Exit\n";
    echo "\nChoice: ";
    $choice = trim(fgets(STDIN));

    switch ($choice) {
        case '1':
            echo "\n";
            showComments($comments, null, []);
            echo "\nPress Enter to continue...";
            fgets(STDIN);
            break;
        case '2':
            $author = prompt('Author (default "You"): ');
            if ($author === '') $author = 'You';
            $text = prompt('Message: ');
            if ($text === '') { echo "Message cannot be empty.\n"; break; }
            $id = postComment($comments, $author, $text, null);
            echo "Posted as ID: $id\n";
            break;
        case '3':
            $replyTo = intval(prompt('Reply to ID: '));
            $parent = getCommentById($comments, $replyTo);
            if (!$parent) { echo "No comment with ID $replyTo\n"; break; }
            $author = prompt('Author (default "You"): ');
            if ($author === '') $author = 'You';
            $text = prompt('Message: ');
            if ($text === '') { echo "Message cannot be empty.\n"; break; }
            $id = postComment($comments, $author, $text, $replyTo);
            echo "Reply posted as ID: $id\n";
            break;
        case '4':
            $delId = intval(prompt('Delete ID (branch): '));
            $target = getCommentById($comments, $delId);
            if (!$target) { echo "No comment with ID $delId\n"; break; }
            $deleted = deleteBranch($comments, $delId);
            echo "Deleted IDs: " . implode(', ', $deleted) . "\n";
            break;
        case '5':
            $id = intval(prompt('Which comment ID? '));
            $ancestor = findAncestor($comments, $id, 3);
            if ($ancestor === null) echo "No great-grandparent found (less than 3 levels).\n";
            else echo "Great-grandparent for ID $id is ID: $ancestor\n";
            break;
        case '6':
            echo "Goodbye!\n";
            exit(0);
        default:
            echo "Unknown choice.\n";
    }
}
